# To build an image from this file, run the following command:
#     sudo docker image build ../../ -f Dockerfile.dev -t sofaster-dev

# We're going to use an image with dependencies pre-installed as our base
# for developing and testing SoFASTER.
FROM sofaster-deps AS build

# Copy all SoFASTER source code into the container.
WORKDIR "/"
RUN mkdir SoFASTER
RUN mkdir SoFASTER/cc
RUN mkdir SoFASTER/scripts

COPY cc ./SoFASTER/cc/
COPY scripts ./SoFASTER/scripts/

# Setup Makefiles, azure and mellanox drivers within the container.
WORKDIR "./SoFASTER"
RUN ["scripts/common/sofaster.sh"]
