//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTER.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FASTER.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AsyncIO {
            get {
                return ResourceManager.GetString("AsyncIO", resourceCulture);
            }
        }
        
        internal static string AsyncResultTypes {
            get {
                return ResourceManager.GetString("AsyncResultTypes", resourceCulture);
            }
        }
        
        internal static string Checkpoint {
            get {
                return ResourceManager.GetString("Checkpoint", resourceCulture);
            }
        }
        
        internal static string Contexts {
            get {
                return ResourceManager.GetString("Contexts", resourceCulture);
            }
        }
        
        internal static string FASTER {
            get {
                return ResourceManager.GetString("FASTER", resourceCulture);
            }
        }
        
        internal static string FASTERBase {
            get {
                return ResourceManager.GetString("FASTERBase", resourceCulture);
            }
        }
        
        internal static string FASTERImpl {
            get {
                return ResourceManager.GetString("FASTERImpl", resourceCulture);
            }
        }
        
        internal static string FASTERThread {
            get {
                return ResourceManager.GetString("FASTERThread", resourceCulture);
            }
        }
        
        internal static string IFASTER_Mixed {
            get {
                return ResourceManager.GetString("IFASTER_Mixed", resourceCulture);
            }
        }
        
        internal static string IndexCheckpoint {
            get {
                return ResourceManager.GetString("IndexCheckpoint", resourceCulture);
            }
        }
        
        internal static string IndexRecovery {
            get {
                return ResourceManager.GetString("IndexRecovery", resourceCulture);
            }
        }
        
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        internal static string MixedContextWrapper {
            get {
                return ResourceManager.GetString("MixedContextWrapper", resourceCulture);
            }
        }
        
        internal static string MixedFunctionsWrapper {
            get {
                return ResourceManager.GetString("MixedFunctionsWrapper", resourceCulture);
            }
        }
        
        internal static string MixedInputWrapper {
            get {
                return ResourceManager.GetString("MixedInputWrapper", resourceCulture);
            }
        }
        
        internal static string MixedKeyWrapper {
            get {
                return ResourceManager.GetString("MixedKeyWrapper", resourceCulture);
            }
        }
        
        internal static string MixedManagedFAST {
            get {
                return ResourceManager.GetString("MixedManagedFAST", resourceCulture);
            }
        }
        
        internal static string MixedOutputWrapper {
            get {
                return ResourceManager.GetString("MixedOutputWrapper", resourceCulture);
            }
        }
        
        internal static string MixedUnwrappedTypes {
            get {
                return ResourceManager.GetString("MixedUnwrappedTypes", resourceCulture);
            }
        }
        
        internal static string MixedUserFunctions {
            get {
                return ResourceManager.GetString("MixedUserFunctions", resourceCulture);
            }
        }
        
        internal static string MixedValueWrapper {
            get {
                return ResourceManager.GetString("MixedValueWrapper", resourceCulture);
            }
        }
        
        internal static string PersistentMemoryMalloc {
            get {
                return ResourceManager.GetString("PersistentMemoryMalloc", resourceCulture);
            }
        }
        
        internal static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
    }
}
